/**
 * Framework error model.
 *
 * Wire format follows RFC 9457 (application/problem+json) so clients
 * across teams and languages have a predictable, OpenAPI-documentable
 * error shape.
 *
 * Production-mode rendering scrubs `detail` for 5xx responses so internal
 * messages never leak to clients (security: information disclosure).
 */

/**
 * RFC 9457 Problem Details document. This is the on-the-wire shape DaloyJS
 * uses for **every** error response (the `Content-Type` is
 * `application/problem+json`). Clients in any language can decode the same
 * structure.
 *
 * Custom fields are allowed and pass through the JSON serialization
 * unchanged — handy for correlation ids, retry hints, or business codes.
 *
 * @see https://www.rfc-editor.org/rfc/rfc9457.html
 * @since 0.1.0
 */
export interface ProblemDetails {
  /** URI reference identifying the problem type (dereferenceable when possible). */
  type: string;
  /** Short, human-readable summary of the problem (stable across occurrences). */
  title: string;
  /** HTTP status code generated by the origin server. */
  status: number;
  /** Human-readable explanation specific to this occurrence. Scrubbed for 5xx in production. */
  detail?: string;
  /** URI reference identifying the specific occurrence (e.g. `urn:request:abc123`). */
  instance?: string;
  /** DaloyJS extension: structured validation issues with JSON Pointer-style paths. */
  errors?: Array<{ path: string; message: string }>;
  /** Arbitrary additional members (RFC 9457 §3.2). */
  [key: string]: unknown;
}

/**
 * Options for {@link HttpError.toResponse}.
 *
 * @since 0.1.0
 */
export interface ProblemRenderOptions {
  /** Scrub `detail` from 5xx responses. Defaults to `process.env.NODE_ENV === "production"`. */
  production?: boolean;
  /** Request id stamped into `instance` as `urn:request:<id>` for log correlation. */
  requestId?: string;
  /**
   * Extra response headers (typically `ctx.set.headers`) to merge
   * onto the rendered problem response so per-request state (CSRF rotation,
   * session renewal, request-id, secure-headers) is not lost when a handler
   * throws an {@link HttpError}. Existing headers baked into the error
   * (e.g. `cache-control: no-store` on `UnauthorizedError`) win over the
   * supplied set — they were declared by the error class for a reason and
   * are not overridable by ad-hoc Context state.
   *
   * @since 0.32.0
   */
  contextHeaders?: Headers | HeadersInit;
}

/**
 * Headers that are safe to attach to a custom error response
 * (typically a `WWW-Authenticate` challenge built by an auth helper). Any
 * header outside this allowlist on a custom response would leak state from
 * the request scope into a generic error response and is refused at
 * construction time by {@link httpError}.
 *
 * @since 0.32.0
 */
export const SAFE_CUSTOM_ERROR_RESPONSE_HEADERS: ReadonlySet<string> = new Set([
  "www-authenticate",
  "proxy-authenticate",
  "retry-after",
  "content-type",
  "content-language",
  "content-length",
  // `cache-control` is allowed only when its value is `no-store` or
  // `no-cache`; that constraint is enforced in the check itself.
  "cache-control",
]);

/**
 * Thrown when {@link httpError} is asked to attach a custom
 * `Response` whose headers would leak request-scoped state (cookies,
 * caching directives other than `no-store` / `no-cache`, server-timing,
 * `X-*-Token` debug headers) into the error response.
 *
 * @since 0.32.0
 */
export class MessageLeakError extends Error {
  readonly offendingHeaders: ReadonlyArray<{ name: string; reason: string }>;
  constructor(
    offendingHeaders: ReadonlyArray<{ name: string; reason: string }>,
  ) {
    const summary = offendingHeaders
      .map((h) => `${h.name} (${h.reason})`)
      .join(", ");
    super(
      `httpError({ res }): custom error response carries disallowed header(s): ${summary}. ` +
        "Only WWW-Authenticate, Proxy-Authenticate, Retry-After, Content-Type, " +
        "Content-Language, Content-Length, and Cache-Control (no-store|no-cache) " +
        "are permitted on a custom error response.",
    );
    this.name = "MessageLeakError";
    this.offendingHeaders = offendingHeaders;
  }
}

/**
 * @internal — header-safety check applied by {@link httpError} when a custom
 * `res` is supplied. Exported for audits and tests.
 */
export function checkCustomErrorResponseHeaders(
  headers: Headers,
): Array<{ name: string; reason: string }> {
  const offending: Array<{ name: string; reason: string }> = [];
  headers.forEach((value, name) => {
    const lower = name.toLowerCase();
    if (lower === "cache-control") {
      const token = value.trim().toLowerCase();
      if (token !== "no-store" && token !== "no-cache") {
        offending.push({
          name,
          reason: `cache-control must be "no-store" or "no-cache"; got ${JSON.stringify(value)}`,
        });
      }
      return;
    }
    if (lower === "set-cookie" || lower === "set-cookie2") {
      offending.push({ name, reason: "cookies are not permitted on a generic error response" });
      return;
    }
    if (lower === "server-timing") {
      offending.push({ name, reason: "Server-Timing is a side-channel leak in error responses" });
      return;
    }
    if (lower.startsWith("x-") && lower.endsWith("-token")) {
      offending.push({ name, reason: "X-*-Token headers are request-scoped" });
      return;
    }
    if (!SAFE_CUSTOM_ERROR_RESPONSE_HEADERS.has(lower)) {
      offending.push({ name, reason: "not in the safe-custom-error-response allowlist" });
    }
  });
  return offending;
}

function defaultIsProduction(): boolean {
  return typeof process !== "undefined" && process.env?.NODE_ENV === "production";
}

function defaultSecureDefaults(): boolean {
  // Mirrors App({ secureDefaults: true }) — on unless explicitly opted out.
  return true;
}

function isSafeCustomErrorHeaderValue(name: string, value: string): boolean {
  const lower = name.toLowerCase();
  return (
    SAFE_CUSTOM_ERROR_RESPONSE_HEADERS.has(lower) &&
    !(lower === "cache-control" &&
      value.trim().toLowerCase() !== "no-store" &&
      value.trim().toLowerCase() !== "no-cache")
  );
}

function shouldCopyCustomErrorHeader(name: string, value: string): boolean {
  if (!isSafeCustomErrorHeaderValue(name, value)) return false;
  // The custom Response body is intentionally ignored by httpError({ res });
  // forwarding its Content-Length would describe the wrong problem+json body.
  return name.toLowerCase() !== "content-length";
}

/**
 * Factory for constructing an {@link HttpError} with an optional
 * custom `res` (typically a `WWW-Authenticate` challenge). Refuses-at-
 * construction in production under `secureDefaults` when the custom
 * response carries headers that would leak request-scoped state — see
 * {@link SAFE_CUSTOM_ERROR_RESPONSE_HEADERS} and {@link MessageLeakError}.
 *
 * @since 0.32.0
 */
export interface HttpErrorOptions {
  status: number;
  problem: Partial<ProblemDetails> & { title: string };
  /** Plain headers merged onto the rendered response. */
  headers?: Record<string, string>;
  /**
   * Custom `Response` providing additional headers (typically a
   * `WWW-Authenticate` challenge). Body is ignored; only headers are
   * extracted. Headers are validated against the safe allowlist.
   */
  res?: Response;
  /**
   * Override the production check. Defaults to
   * `process.env.NODE_ENV === "production"`.
   */
  production?: boolean;
  /**
   * Override the secureDefaults check. Defaults to `true`. The refuse-at-
   * construction behavior only activates when `production && secureDefaults`
   * are both true.
   */
  secureDefaults?: boolean;
}

/**
 * Build an {@link HttpError} with optional safe-header extraction from a
 * custom `Response`. See {@link HttpErrorOptions}.
 *
 * @since 0.32.0
 */
export function httpError(opts: HttpErrorOptions): HttpError {
  const headers = new Headers(opts.headers);
  if (opts.res) {
    const isProd = opts.production ?? defaultIsProduction();
    const secureDefaults = opts.secureDefaults ?? defaultSecureDefaults();
    const offending = checkCustomErrorResponseHeaders(opts.res.headers);
    if (isProd && secureDefaults && offending.length > 0) {
      throw new MessageLeakError(offending);
    }
    opts.res.headers.forEach((value, name) => {
      // Allow the safe headers through; disallowed ones are dropped in
      // non-secureDefaults / dev contexts after a check-only pass.
      if (shouldCopyCustomErrorHeader(name, value)) {
        // Don't overwrite caller-supplied headers.
        if (!headers.has(name)) headers.set(name, value);
      }
    });
  }
  return new HttpError(opts.status, opts.problem, Object.fromEntries(headers.entries()));
}

/**
 * Base class for every DaloyJS HTTP error.
 *
 * Throwing an `HttpError` (or any subclass) anywhere inside a handler, hook,
 * or middleware causes DaloyJS to serialize it as RFC 9457 problem+json with
 * the appropriate status code and (optionally) extra response headers such as
 * `Retry-After` or `Allow`. In production mode, 5xx `detail` is scrubbed to
 * avoid information disclosure.
 *
 * **Security note:** only **5xx** `detail` is scrubbed in production. A `4xx`
 * `detail` is always returned to the client (it is assumed to be
 * client-actionable), so never place secrets or internal diagnostics in the
 * `detail` of a 4xx error.
 *
 * Prefer the dedicated subclasses (`BadRequestError`, `NotFoundError`, ...)
 * for common statuses; instantiate `HttpError` directly only for unusual
 * status codes or fully-custom problem documents.
 *
 * @example
 * ```ts
 * import { HttpError } from "@daloyjs/core";
 *
 * app.route({
 *   method: "GET",
 *   path: "/teapot",
 *   responses: { 418: { description: "I'm a teapot" } },
 *   handler: () => {
 *     throw new HttpError(418, {
 *       type: "https://example.com/errors/teapot",
 *       title: "I'm a teapot",
 *       detail: "Short and stout",
 *     });
 *   },
 * });
 * ```
 *
 * @since 0.1.0
 */
export class HttpError extends Error {
  readonly status: number;
  readonly problem: ProblemDetails;
  readonly headers?: Record<string, string>;

  constructor(
    status: number,
    problem: Partial<ProblemDetails> & { title: string },
    headers?: Record<string, string>
  ) {
    super(problem.title);
    this.name = "HttpError";
    this.status = status;
    this.problem = {
      type: problem.type ?? `https://httpstatuses.io/${status}`,
      ...problem,
      title: problem.title,
      status,
    };
    if (headers) this.headers = headers;
  }

  /**
   * Render this error as a `Response` whose body is the problem+json document.
   * Used internally by the framework; safe to call from custom `onError` hooks
   * that want to forward additional headers.
   *
   * @param opts - Rendering options (production scrubbing, correlation id).
   * @returns A `Response` with `Content-Type: application/problem+json`.
   */
  toResponse(opts: ProblemRenderOptions = {}): Response {
    const isProd =
      opts.production ??
      (typeof process !== "undefined" && process.env?.NODE_ENV === "production");
    const out: ProblemDetails = { ...this.problem };
    if (isProd && this.status >= 500) {
      delete out.detail; // do not leak internals
    }
    if (opts.requestId) out.instance = `urn:request:${opts.requestId}`;
    const headers = new Headers({ "content-type": "application/problem+json" });
    // Skip the Object.entries({}) churn on the common case where the
    // error was constructed without extra response headers.
    if (this.headers !== undefined) {
      for (const [name, value] of Object.entries(this.headers)) {
        headers.set(name, value);
      }
    }
    // Merge Context.set.headers (CSRF rotation, session renewal,
    // request-id, secureHeaders output) without overriding headers the
    // error class baked in (e.g. `cache-control: no-store` on auth
    // failures). The framework already merges these at the dispatch
    // boundary; this branch lets direct callers (custom `onError` hooks,
    // tests) get the same behavior.
    if (opts.contextHeaders) {
      const ctxHeaders =
        opts.contextHeaders instanceof Headers
          ? opts.contextHeaders
          : new Headers(opts.contextHeaders);
      ctxHeaders.forEach((value, name) => {
        if (!headers.has(name)) headers.set(name, value);
      });
    }
    return new Response(JSON.stringify(out), { status: this.status, headers });
  }
}

/**
 * `400 Bad Request` — the request is syntactically invalid or otherwise
 * malformed in a way the client should be able to fix without retrying.
 *
 * @example
 * ```ts
 * throw new BadRequestError("`since` must be an ISO-8601 timestamp");
 * ```
 *
 * @param detail - Optional human-readable explanation surfaced to the client.
 * @since 0.1.0
 */
export class BadRequestError extends HttpError {
  constructor(detail?: string) {
    super(400, {
      type: "https://daloyjs.dev/errors/bad-request",
      title: "Bad Request",
      ...(detail ? { detail } : {}),
    });
    this.name = "BadRequestError";
  }
}

/**
 * `422 Unprocessable Entity` — raised automatically when DaloyJS' request
 * validator rejects `params`, `query`, `headers`, or `body`. The reported
 * issues are surfaced in the `errors` member of the problem document so
 * frontends can render field-level feedback without reparsing the message.
 *
 * Throw this directly only when implementing custom validation outside the
 * declared schema.
 *
 * @param where - Which part of the request failed validation.
 * @param issues - Array of `{ path, message }` records (one per failure).
 * @since 0.1.0
 */
export class ValidationError extends HttpError {
  constructor(
    where: "params" | "query" | "headers" | "body",
    issues: Array<{ path: string; message: string }>
  ) {
    super(422, {
      type: "https://daloyjs.dev/errors/validation",
      title: "Request validation failed",
      detail: `Invalid ${where}`,
      errors: issues,
    });
    this.name = "ValidationError";
  }
}

/**
 * `404 Not Found` — the requested resource does not exist.
 * DaloyJS also throws this internally for routes the router did not match.
 *
 * @param detail - Optional human-readable explanation (e.g. resource id).
 * @since 0.1.0
 */
export class NotFoundError extends HttpError {
  constructor(detail?: string) {
    super(404, {
      type: "https://daloyjs.dev/errors/not-found",
      title: "Not Found",
      ...(detail ? { detail } : {}),
    });
    this.name = "NotFoundError";
  }
}

/**
 * `409 Conflict` — the request could not be completed because it conflicts
 * with the current state of the target resource. The built-in
 * {@link idempotency} middleware throws this when a second request arrives
 * with an `Idempotency-Key` that is still being processed by an in-flight
 * request (the original response has not been produced yet). The response
 * carries `Cache-Control: no-store` so a private cache cannot mask the
 * conflict.
 *
 * @param detail - Optional human-readable explanation surfaced to the client.
 * @since 0.37.0
 */
export class ConflictError extends HttpError {
  constructor(detail?: string) {
    super(
      409,
      {
        type: "https://daloyjs.dev/errors/conflict",
        title: "Conflict",
        ...(detail ? { detail } : {}),
      },
      { "cache-control": "no-store" }
    );
    this.name = "ConflictError";
  }
}

/**
 * `401 Unauthorized` — authentication is required and missing or invalid.
 * Pair with a `WWW-Authenticate` header on the response when issuing a
 * challenge (the built-in `bearerAuth` middleware does this for you).
 *
 * @param detail - Optional human-readable explanation surfaced to the client.
 * @since 0.1.0
 */
export class UnauthorizedError extends HttpError {
  constructor(detail?: string) {
    super(
      401,
      {
        type: "https://daloyjs.dev/errors/unauthorized",
        title: "Unauthorized",
        ...(detail ? { detail } : {}),
      },
      // Auth-failure responses must never be cached. `no-store`
      // already forbids both shared and private caches per RFC 9111 §5.2.2.5.
      { "cache-control": "no-store" },
    );
    this.name = "UnauthorizedError";
  }
}

/**
 * `403 Forbidden` — the request is authenticated but not permitted.
 * Use for authorization failures ("who you are" is fine, "what you're asking
 * for" is not). Used by built-in CSRF and bearer-token middleware.
 *
 * @param detail - Optional human-readable explanation surfaced to the client.
 * @since 0.1.0
 */
export class ForbiddenError extends HttpError {
  constructor(detail?: string) {
    super(
      403,
      {
        type: "https://daloyjs.dev/errors/forbidden",
        title: "Forbidden",
        ...(detail ? { detail } : {}),
      },
      // Authorization-failure responses must never be cached.
      { "cache-control": "no-store" },
    );
    this.name = "ForbiddenError";
  }
}

/**
 * `405 Method Not Allowed` — thrown automatically by the router when a path
 * matches but no route is registered for the request method. The response
 * carries an `Allow` header enumerating the supported methods, as required by
 * the HTTP spec.
 *
 * @param allow - List of HTTP method names supported on the matched path.
 * @since 0.1.0
 */
export class MethodNotAllowedError extends HttpError {
  constructor(allow: string[]) {
    super(
      405,
      {
        type: "https://daloyjs.dev/errors/method-not-allowed",
        title: "Method Not Allowed",
      },
      { allow: allow.join(", ") }
    );
    this.name = "MethodNotAllowedError";
  }
}

/**
 * `413 Payload Too Large` — thrown by `readBodyLimited` when an incoming
 * request body exceeds {@link AppOptions.bodyLimitBytes} (or a tighter
 * per-route limit). Trips both on the declared `Content-Length` (fail-fast)
 * and on the actual streamed byte count (defence in depth).
 *
 * @param limit - The configured byte cap that was exceeded.
 * @since 0.1.0
 */
export class PayloadTooLargeError extends HttpError {
  constructor(limit: number) {
    super(413, {
      type: "https://daloyjs.dev/errors/payload-too-large",
      title: "Payload Too Large",
      detail: `Body exceeds ${limit} bytes`,
    });
    this.name = "PayloadTooLargeError";
  }
}

/**
 * `415 Unsupported Media Type` — thrown when the request `Content-Type` is
 * not in {@link AppOptions.allowedContentTypes} for a route that declares a
 * body schema.
 *
 * @param got - The `Content-Type` value the client sent.
 * @param expected - Allowed media types for the route.
 * @since 0.1.0
 */
export class UnsupportedMediaTypeError extends HttpError {
  constructor(got: string, expected: string[]) {
    super(415, {
      type: "https://daloyjs.dev/errors/unsupported-media-type",
      title: "Unsupported Media Type",
      detail: `Got "${got}", expected one of: ${expected.join(", ")}`,
    });
    this.name = "UnsupportedMediaTypeError";
  }
}

/**
 * `429 Too Many Requests` — thrown by the built-in `rateLimit` middleware
 * when the caller exceeds its quota. When `retryAfterSeconds` is provided the
 * response carries a `Retry-After` header; clients should back off for that
 * many seconds before retrying.
 *
 * @param retryAfterSeconds - Seconds the client should wait before retrying.
 * @since 0.1.0
 */
export class TooManyRequestsError extends HttpError {
  constructor(retryAfterSeconds?: number) {
    super(
      429,
      {
        type: "https://daloyjs.dev/errors/too-many-requests",
        title: "Too Many Requests",
      },
      // Rate-limit responses must never be cached so a 429 from a
      // private cache cannot extend the throttle window past `Retry-After`.
      retryAfterSeconds !== undefined
        ? { "retry-after": String(retryAfterSeconds), "cache-control": "no-store" }
        : { "cache-control": "no-store" }
    );
    this.name = "TooManyRequestsError";
  }
}

/**
 * `408 Request Timeout` — thrown when a handler exceeds
 * {@link AppOptions.requestTimeoutMs}. The framework aborts the in-flight
 * handler when this fires (handlers should respect the `AbortSignal` on
 * `ctx.request.signal` to clean up).
 *
 * @param ms - The configured timeout that was exceeded.
 * @since 0.1.0
 */
export class RequestTimeoutError extends HttpError {
  constructor(ms: number) {
    super(408, {
      type: "https://daloyjs.dev/errors/request-timeout",
      title: "Request Timeout",
      detail: `Request exceeded ${ms}ms`,
    });
    this.name = "RequestTimeoutError";
  }
}

/**
 * `500 Internal Server Error` — generic fallback used by the framework when
 * a handler throws something that isn't an `HttpError`. The original error is
 * logged at `error` level with the request id for correlation. The `detail`
 * is automatically scrubbed in production mode.
 *
 * @param detail - Optional explanation; suppressed in production output.
 * @since 0.1.0
 */
export class InternalError extends HttpError {
  constructor(detail?: string) {
    super(500, {
      type: "https://daloyjs.dev/errors/internal",
      title: "Internal Server Error",
      ...(detail ? { detail } : {}),
    });
    this.name = "InternalError";
  }
}
