/**
 * Framework error model.
 *
 * Wire format follows RFC 9457 (application/problem+json) so clients
 * across teams and languages have a predictable, OpenAPI-documentable
 * error shape.
 *
 * Production-mode rendering scrubs `detail` for 5xx responses so internal
 * messages never leak to clients (security: information disclosure).
 */

/**
 * RFC 9457 Problem Details document. This is the on-the-wire shape DaloyJS
 * uses for **every** error response (the `Content-Type` is
 * `application/problem+json`). Clients in any language can decode the same
 * structure.
 *
 * Custom fields are allowed and pass through the JSON serialization
 * unchanged — handy for correlation ids, retry hints, or business codes.
 *
 * @see https://www.rfc-editor.org/rfc/rfc9457.html
 * @since 0.1.0
 */
export interface ProblemDetails {
  /** URI reference identifying the problem type (dereferenceable when possible). */
  type: string;
  /** Short, human-readable summary of the problem (stable across occurrences). */
  title: string;
  /** HTTP status code generated by the origin server. */
  status: number;
  /** Human-readable explanation specific to this occurrence. Scrubbed for 5xx in production. */
  detail?: string;
  /** URI reference identifying the specific occurrence (e.g. `urn:request:abc123`). */
  instance?: string;
  /** DaloyJS extension: structured validation issues with JSON Pointer-style paths. */
  errors?: Array<{ path: string; message: string }>;
  /** Arbitrary additional members (RFC 9457 §3.2). */
  [key: string]: unknown;
}

/**
 * Options for {@link HttpError.toResponse}.
 *
 * @since 0.1.0
 */
export interface ProblemRenderOptions {
  /** Scrub `detail` from 5xx responses. Defaults to `process.env.NODE_ENV === "production"`. */
  production?: boolean;
  /** Request id stamped into `instance` as `urn:request:<id>` for log correlation. */
  requestId?: string;
}

/**
 * Base class for every DaloyJS HTTP error.
 *
 * Throwing an `HttpError` (or any subclass) anywhere inside a handler, hook,
 * or middleware causes DaloyJS to serialize it as RFC 9457 problem+json with
 * the appropriate status code and (optionally) extra response headers such as
 * `Retry-After` or `Allow`. In production mode, 5xx `detail` is scrubbed to
 * avoid information disclosure.
 *
 * Prefer the dedicated subclasses (`BadRequestError`, `NotFoundError`, ...)
 * for common statuses; instantiate `HttpError` directly only for unusual
 * status codes or fully-custom problem documents.
 *
 * @example
 * ```ts
 * import { HttpError } from "@daloyjs/core";
 *
 * app.route({
 *   method: "GET",
 *   path: "/teapot",
 *   responses: { 418: { description: "I'm a teapot" } },
 *   handler: () => {
 *     throw new HttpError(418, {
 *       type: "https://example.com/errors/teapot",
 *       title: "I'm a teapot",
 *       detail: "Short and stout",
 *     });
 *   },
 * });
 * ```
 *
 * @since 0.1.0
 */
export class HttpError extends Error {
  readonly status: number;
  readonly problem: ProblemDetails;
  readonly headers?: Record<string, string>;

  constructor(
    status: number,
    problem: Partial<ProblemDetails> & { title: string },
    headers?: Record<string, string>
  ) {
    super(problem.title);
    this.name = "HttpError";
    this.status = status;
    this.problem = {
      type: problem.type ?? `https://httpstatuses.io/${status}`,
      ...problem,
      title: problem.title,
      status,
    };
    if (headers) this.headers = headers;
  }

  /**
   * Render this error as a `Response` whose body is the problem+json document.
   * Used internally by the framework; safe to call from custom `onError` hooks
   * that want to forward additional headers.
   *
   * @param opts - Rendering options (production scrubbing, correlation id).
   * @returns A `Response` with `Content-Type: application/problem+json`.
   */
  toResponse(opts: ProblemRenderOptions = {}): Response {
    const isProd =
      opts.production ??
      (typeof process !== "undefined" && process.env?.NODE_ENV === "production");
    const out: ProblemDetails = { ...this.problem };
    if (isProd && this.status >= 500) {
      delete out.detail; // do not leak internals
    }
    if (opts.requestId) out.instance = `urn:request:${opts.requestId}`;
    const headers: Record<string, string> = {
      "content-type": "application/problem+json",
      ...(this.headers ?? {}),
    };
    return new Response(JSON.stringify(out), { status: this.status, headers });
  }
}

/**
 * `400 Bad Request` — the request is syntactically invalid or otherwise
 * malformed in a way the client should be able to fix without retrying.
 *
 * @example
 * ```ts
 * throw new BadRequestError("`since` must be an ISO-8601 timestamp");
 * ```
 *
 * @param detail - Optional human-readable explanation surfaced to the client.
 * @since 0.1.0
 */
export class BadRequestError extends HttpError {
  constructor(detail?: string) {
    super(400, {
      type: "https://daloyjs.dev/errors/bad-request",
      title: "Bad Request",
      ...(detail ? { detail } : {}),
    });
    this.name = "BadRequestError";
  }
}

/**
 * `422 Unprocessable Entity` — raised automatically when DaloyJS' request
 * validator rejects `params`, `query`, `headers`, or `body`. The reported
 * issues are surfaced in the `errors` member of the problem document so
 * frontends can render field-level feedback without reparsing the message.
 *
 * Throw this directly only when implementing custom validation outside the
 * declared schema.
 *
 * @param where - Which part of the request failed validation.
 * @param issues - Array of `{ path, message }` records (one per failure).
 * @since 0.1.0
 */
export class ValidationError extends HttpError {
  constructor(
    where: "params" | "query" | "headers" | "body",
    issues: Array<{ path: string; message: string }>
  ) {
    super(422, {
      type: "https://daloyjs.dev/errors/validation",
      title: "Request validation failed",
      detail: `Invalid ${where}`,
      errors: issues,
    });
    this.name = "ValidationError";
  }
}

/**
 * `404 Not Found` — the requested resource does not exist.
 * DaloyJS also throws this internally for routes the router did not match.
 *
 * @param detail - Optional human-readable explanation (e.g. resource id).
 * @since 0.1.0
 */
export class NotFoundError extends HttpError {
  constructor(detail?: string) {
    super(404, {
      type: "https://daloyjs.dev/errors/not-found",
      title: "Not Found",
      ...(detail ? { detail } : {}),
    });
    this.name = "NotFoundError";
  }
}

/**
 * `401 Unauthorized` — authentication is required and missing or invalid.
 * Pair with a `WWW-Authenticate` header on the response when issuing a
 * challenge (the built-in `bearerAuth` middleware does this for you).
 *
 * @param detail - Optional human-readable explanation surfaced to the client.
 * @since 0.1.0
 */
export class UnauthorizedError extends HttpError {
  constructor(detail?: string) {
    super(401, {
      type: "https://daloyjs.dev/errors/unauthorized",
      title: "Unauthorized",
      ...(detail ? { detail } : {}),
    });
    this.name = "UnauthorizedError";
  }
}

/**
 * `403 Forbidden` — the request is authenticated but not permitted.
 * Use for authorization failures ("who you are" is fine, "what you're asking
 * for" is not). Used by built-in CSRF and bearer-token middleware.
 *
 * @param detail - Optional human-readable explanation surfaced to the client.
 * @since 0.1.0
 */
export class ForbiddenError extends HttpError {
  constructor(detail?: string) {
    super(403, {
      type: "https://daloyjs.dev/errors/forbidden",
      title: "Forbidden",
      ...(detail ? { detail } : {}),
    });
    this.name = "ForbiddenError";
  }
}

/**
 * `405 Method Not Allowed` — thrown automatically by the router when a path
 * matches but no route is registered for the request method. The response
 * carries an `Allow` header enumerating the supported methods, as required by
 * the HTTP spec.
 *
 * @param allow - List of HTTP method names supported on the matched path.
 * @since 0.1.0
 */
export class MethodNotAllowedError extends HttpError {
  constructor(allow: string[]) {
    super(
      405,
      {
        type: "https://daloyjs.dev/errors/method-not-allowed",
        title: "Method Not Allowed",
      },
      { allow: allow.join(", ") }
    );
    this.name = "MethodNotAllowedError";
  }
}

/**
 * `413 Payload Too Large` — thrown by `readBodyLimited` when an incoming
 * request body exceeds {@link AppOptions.bodyLimitBytes} (or a tighter
 * per-route limit). Trips both on the declared `Content-Length` (fail-fast)
 * and on the actual streamed byte count (defence in depth).
 *
 * @param limit - The configured byte cap that was exceeded.
 * @since 0.1.0
 */
export class PayloadTooLargeError extends HttpError {
  constructor(limit: number) {
    super(413, {
      type: "https://daloyjs.dev/errors/payload-too-large",
      title: "Payload Too Large",
      detail: `Body exceeds ${limit} bytes`,
    });
    this.name = "PayloadTooLargeError";
  }
}

/**
 * `415 Unsupported Media Type` — thrown when the request `Content-Type` is
 * not in {@link AppOptions.allowedContentTypes} for a route that declares a
 * body schema.
 *
 * @param got - The `Content-Type` value the client sent.
 * @param expected - Allowed media types for the route.
 * @since 0.1.0
 */
export class UnsupportedMediaTypeError extends HttpError {
  constructor(got: string, expected: string[]) {
    super(415, {
      type: "https://daloyjs.dev/errors/unsupported-media-type",
      title: "Unsupported Media Type",
      detail: `Got "${got}", expected one of: ${expected.join(", ")}`,
    });
    this.name = "UnsupportedMediaTypeError";
  }
}

/**
 * `429 Too Many Requests` — thrown by the built-in `rateLimit` middleware
 * when the caller exceeds its quota. When `retryAfterSeconds` is provided the
 * response carries a `Retry-After` header; clients should back off for that
 * many seconds before retrying.
 *
 * @param retryAfterSeconds - Seconds the client should wait before retrying.
 * @since 0.1.0
 */
export class TooManyRequestsError extends HttpError {
  constructor(retryAfterSeconds?: number) {
    super(
      429,
      {
        type: "https://daloyjs.dev/errors/too-many-requests",
        title: "Too Many Requests",
      },
      retryAfterSeconds !== undefined
        ? { "retry-after": String(retryAfterSeconds) }
        : undefined
    );
    this.name = "TooManyRequestsError";
  }
}

/**
 * `408 Request Timeout` — thrown when a handler exceeds
 * {@link AppOptions.requestTimeoutMs}. The framework aborts the in-flight
 * handler when this fires (handlers should respect the `AbortSignal` on
 * `ctx.request.signal` to clean up).
 *
 * @param ms - The configured timeout that was exceeded.
 * @since 0.1.0
 */
export class RequestTimeoutError extends HttpError {
  constructor(ms: number) {
    super(408, {
      type: "https://daloyjs.dev/errors/request-timeout",
      title: "Request Timeout",
      detail: `Request exceeded ${ms}ms`,
    });
    this.name = "RequestTimeoutError";
  }
}

/**
 * `500 Internal Server Error` — generic fallback used by the framework when
 * a handler throws something that isn't an `HttpError`. The original error is
 * logged at `error` level with the request id for correlation. The `detail`
 * is automatically scrubbed in production mode.
 *
 * @param detail - Optional explanation; suppressed in production output.
 * @since 0.1.0
 */
export class InternalError extends HttpError {
  constructor(detail?: string) {
    super(500, {
      type: "https://daloyjs.dev/errors/internal",
      title: "Internal Server Error",
      ...(detail ? { detail } : {}),
    });
    this.name = "InternalError";
  }
}
